# Generated by Django 4.2.2 on 2023-07-01 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recording_transcription', '0002_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_natures',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_organizer_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_organizer_profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_organizer_username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_channel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='participants_list',
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.URLField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recording_transcription.meeting')),
            ],
            options={
                'db_table': 'Participant',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants_list',
            field=models.ManyToManyField(related_name='meetings', to='recording_transcription.participant'),
        ),
    ]
