# Generated by Django 4.2.2 on 2023-07-01 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recording_transcription', '0004_rename_meeting_natures_meeting_meeting_nature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting_organizer_email',
            new_name='meeting_organizer_emails',
        ),
    ]
