# Generated by Django 4.2.2 on 2023-07-01 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recording_transcription', '0005_rename_meeting_organizer_email_meeting_meeting_organizer_emails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='meeting_organizer_emails',
            new_name='meeting_organizer_email',
        ),
    ]
