# Generated by Django 4.2.2 on 2023-07-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recording_transcription', '0006_rename_meeting_organizer_emails_meeting_meeting_organizer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='participants_list',
        ),
        migrations.AddField(
            model_name='meeting',
            name='participants_list',
            field=models.ManyToManyField(related_name='meetings', to='recording_transcription.participant'),
        ),
    ]
