# Generated by Django 4.2.2 on 2023-07-01 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recording_transcription', '0007_remove_meeting_participants_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_action_items_count',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Absents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('profile_picture', models.URLField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recording_transcription.meeting')),
            ],
            options={
                'db_table': 'Absents',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='absents_list',
            field=models.ManyToManyField(related_name='meetings_absentsß', to='recording_transcription.absents'),
        ),
    ]
