# Generated by Django 4.2.2 on 2023-07-02 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recording_transcription', '0009_alter_meeting_absents_list_action_item_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='transcript',
            table='Transcript',
        ),
    ]
