# Generated by Django 4.2.2 on 2023-07-03 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recording_transcription', '0010_alter_transcript_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='meeting',
            new_name='meeting_id',
        ),
        migrations.RenameField(
            model_name='transcript',
            old_name='meeting',
            new_name='meeting_id',
        ),
    ]
