# Generated by Django 4.2.2 on 2023-06-24 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recording_transcription', '0002_transcript'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary_text', models.TextField()),
                ('summary_audio', models.BinaryField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recording_transcription.meeting')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recording_transcription.transcript')),
            ],
            options={
                'db_table': 'summaries',
            },
        ),
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('keypoint_id', models.AutoField(primary_key=True, serialize=False)),
                ('keypoint_text', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recording_transcription.meeting')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recording_transcription.transcript')),
            ],
            options={
                'db_table': 'keypoints',
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('agenda_id', models.AutoField(primary_key=True, serialize=False)),
                ('agenda_text', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recording_transcription.meeting')),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recording_transcription.transcript')),
            ],
            options={
                'db_table': 'agendas',
            },
        ),
    ]
